# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(504, 446)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameLast = QtWidgets.QFrame(Form)
        self.frameLast.setStyleSheet("background:lightgreen")
        self.frameLast.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLast.setObjectName("frameLast")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameLast)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelLastTime = QtWidgets.QLabel(self.frameLast)
        self.labelLastTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLastTime.sizePolicy().hasHeightForWidth())
        self.labelLastTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.labelLastTime.setFont(font)
        self.labelLastTime.setStyleSheet("")
        self.labelLastTime.setTextFormat(QtCore.Qt.AutoText)
        self.labelLastTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLastTime.setObjectName("labelLastTime")
        self.verticalLayout_3.addWidget(self.labelLastTime)
        self.line_2 = QtWidgets.QFrame(self.frameLast)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.labelLast = QtWidgets.QLabel(self.frameLast)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelLast.setFont(font)
        self.labelLast.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLast.setObjectName("labelLast")
        self.verticalLayout_3.addWidget(self.labelLast)
        self.verticalLayout.addWidget(self.frameLast)
        self.frameNext = QtWidgets.QFrame(Form)
        self.frameNext.setStyleSheet("background:lightgrey")
        self.frameNext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameNext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameNext.setObjectName("frameNext")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameNext)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelNextTime = QtWidgets.QLabel(self.frameNext)
        self.labelNextTime.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelNextTime.sizePolicy().hasHeightForWidth())
        self.labelNextTime.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.labelNextTime.setFont(font)
        self.labelNextTime.setStyleSheet("")
        self.labelNextTime.setTextFormat(QtCore.Qt.AutoText)
        self.labelNextTime.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNextTime.setObjectName("labelNextTime")
        self.verticalLayout_2.addWidget(self.labelNextTime)
        self.line = QtWidgets.QFrame(self.frameNext)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.labelNext = QtWidgets.QLabel(self.frameNext)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labelNext.setFont(font)
        self.labelNext.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNext.setObjectName("labelNext")
        self.verticalLayout_2.addWidget(self.labelNext)
        self.verticalLayout.addWidget(self.frameNext)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Schedule"))
        self.labelLastTime.setText(_translate("Form", "11:00"))
        self.labelLast.setText(_translate("Form", "TextLabel"))
        self.labelNextTime.setText(_translate("Form", "12:00"))
        self.labelNext.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

